### ISSUE TITLE
Make a repo about awesome-runway!

### ISSUE THREAD

**Issue by Derek-Wds** [runwayml/docs#14]
Hi, I have seen on the documentation website that there should have a `awesome-runway` link in the section `More`. However, it seems that there has no such a link.
If it is needed, I would like to maintain such a repo that lists the examples on the Runwayml web and repos using RunwayML from other Github users.

Thanks,
Derek

**Comment by rubychilds** [comment]
Hi @Derek-Wds Thanks so much for raising an issue with regards to this 👍 . Our documents are going through an overhaul right now, so will be updated soon.

In the meantime, if you can, do a Pull Request and add in the resources that you find. That way we can keep up to date with them and potentially add them into our docs! This will also allow the rest of the community to also update the repo with things they find too

**Comment by Derek-Wds** [comment]
@rubychilds Great! I will make a PR about this as soon as possible.

**Comment by Derek-Wds** [comment]
Hi @rubychilds, I have made a repo about awesome projects with RunwayML [here](https://github.com/Derek-Wds/awesome-runway). I have only found two of them. 
Should I fork this repo and add a new `.md` file or I just transfer the repo I have to RunwayML.

Derek
